version: "3.9"
services:
  dev:
    container_name: dev_container
    build:
      context: ..
      dockerfile: docker/.
    image: abba-app-guide:0.0.1
    depends_on:
      - opensearch-node
    networks:
      - opensearch-net
    stdin_open: true
    tty: true
  
  opensearch-node:
    container_name: opensearch_node
    image: opensearchproject/opensearch:2.11.0
    environment:
      discovery.type: "single-node"
      plugins.security.disabled: "true"
    volumes:
      - ../data/opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - opensearch-net

  opensearch-dashboards:
    container_name: opensearch_dashboards
    image: opensearchproject/opensearch-dashboards:2.11.0
    ports:
      - 5601:5601
    environment:
      - "OPENSEARCH_HOSTS=http://opensearch-node:9200"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net


networks:
  opensearch-net:
    driver: bridge